# Generated by Django 3.1.3 on 2021-07-21 15:17

import core.models.password_reset
import core.models.verification
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=core.models.password_reset._expiration_datetime),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(default=core.models.verification._expiration_datetime),
        ),
    ]
