# Generated by Django 3.1.3 on 2021-07-22 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210721_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('column', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
            ],
        ),
        migrations.CreateModel(
            name='ImpactKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryDocumentImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_document_impacts', to='core.repositorydocument')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_repository_documents', to='core.impact')),
                ('keywords', models.ManyToManyField(related_name='repository_document_impacts', to='core.ImpactKeyword')),
            ],
        ),
        migrations.AddField(
            model_name='impact',
            name='keywords',
            field=models.ManyToManyField(related_name='impacts', to='core.ImpactKeyword'),
        ),
        migrations.CreateModel(
            name='DocumentImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_impacts', to='core.document')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_documents', to='core.impact')),
                ('keywords', models.ManyToManyField(related_name='document_impacts', to='core.ImpactKeyword')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='impacts',
            field=models.ManyToManyField(related_name='documents', through='core.DocumentImpact', to='core.Impact'),
        ),
        migrations.AddField(
            model_name='repositorydocument',
            name='impacts',
            field=models.ManyToManyField(related_name='repository_documents', through='core.RepositoryDocumentImpact', to='core.Impact'),
        ),
        migrations.AddConstraint(
            model_name='repositorydocumentimpact',
            constraint=models.UniqueConstraint(fields=('document', 'impact'), name='unique_repository_document_impact'),
        ),
        migrations.AddConstraint(
            model_name='documentimpact',
            constraint=models.UniqueConstraint(fields=('document', 'impact'), name='unique_document_impact'),
        ),
    ]
