# Generated by Django 3.1.3 on 2021-09-05 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0006_auto_20210905_0408'), ('core', '0007_auto_20210905_1508')]

    dependencies = [
        ('core', '0005_populate_impacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.TextField(default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('scientific', 'scientific'), ('pilot', 'pilot')], default='scientific', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('failed', 'failed'), ('processed', 'processed'), ('dismissed', 'dismissed')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='repositorydocument',
            name='type',
            field=models.IntegerField(choices=[('scientific', 'scientific'), ('pilot', 'pilot')]),
        ),
        migrations.AlterField(
            model_name='repositorydocument',
            name='type',
            field=models.CharField(choices=[('scientific', 'scientific'), ('pilot', 'pilot')], max_length=10),
        ),
    ]
