# Generated by Django 3.1.3 on 2021-09-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210922_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='order',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='repositorycell',
            old_name='order',
            new_name='cell',
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('document', 'cell')},
        ),
    ]
