# Generated by Django 3.1.3 on 2021-10-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='cities',
        ),
        migrations.DeleteModel(
            name='DocumentCity',
        ),
        migrations.AddField(
            model_name='documentlocation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AddField(
            model_name='documentlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='document',
            name='locations',
            field=models.ManyToManyField(related_name='locations', through='core.DocumentLocation', to='core.Location'),
        ),
    ]
