# Generated by Django 3.1.3 on 2021-10-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211017_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDocumentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='repositorydocumentcity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='repositorydocumentcity',
            name='document',
        ),
        migrations.RemoveField(
            model_name='repositorydocument',
            name='cities',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='RepositoryDocumentCity',
        ),
        migrations.AddField(
            model_name='repositorydocumentlocation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repositorydocument'),
        ),
        migrations.AddField(
            model_name='repositorydocumentlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='repositorydocument',
            name='locations',
            field=models.ManyToManyField(through='core.RepositoryDocumentLocation', to='core.Location'),
        ),
    ]
