# Generated by Django 3.1.3 on 2021-11-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211017_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_export_api',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
