# Generated by Django 3.1.3 on 2022-03-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_create_unknown_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_title',
        ),
    ]
