# Generated by Django 3.1.3 on 2022-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220318_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
