# Generated by Django 3.1.3 on 2022-08-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220329_1036'),
        ('core', '0016_location_updated_at'),
    ]

    operations = [
    ]
