# Generated by Django 3.1.3 on 2022-08-08 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20220808_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
