# Generated by Django 3.1.3 on 2022-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220808_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
