"""
Django settings for mesoc_api project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1(9g@&*=vk@bapc77qy1e*28zhj%j*p-90ud*m6elj%g(w1nl-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['api.mesoc.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core.apps.CoreConfig',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mesoc_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mesoc_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/etc/mysql/my.cnf'
        },
        'USER': 'mesoc-api',
        'PASSWORD': 'WB(4)NDz',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'NAME': 'mesoc_api'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.User'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email

EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@mail.mesoc.dev'

CORE_FEEDBACK_EMAIL = 'info@mesoc-project.eu'

ANYMAIL = {
    'IGNORE_RECIPIENT_STATUS': True,

    'MAILGUN_API_KEY': '8e50c6c42b5d016116b4d2ae6eae0138-4de08e90-5e28567d',
    'MAILGUN_API_URL': 'https://api.eu.mailgun.net/v3',
}

# Verification and password reset
CORE_API_BASE_URL = 'http://localhost:8000'
CORE_VERIFICATION_BASE_URL = 'https://app.mesoc.dev/verification'
CORE_PASSWORD_RESET_BASE_URL = 'https://app.mesoc.dev/password_reset'
CORE_PROCESSING_SUCCESS_URL = 'https://app.mesoc.dev/my-documents'
CORE_PROCESSING_FAIL_URL = 'https://app.mesoc.dev/upload-document'

CORE_VERIFICATION_MAX_AGE = 14
CORE_PASSWORD_RESET_MAX_AGE = 14

# Celery

CELERY_BROKER_URL = 'redis://localhost:6379'

# Rest framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.BearerTokenAuthentication'
    ],

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ],

    'DEFAULT_METADATA_CLASS': None
}

# CORS

CORS_ALLOWED_ORIGINS = [
    'https://app.mesoc.dev'
]

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{levelname}] {asctime} {module}: {message}',
            'style': '{'
        }
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/mesoc/mesoc_api.log',
            'maxBytes': 10485760,  # 10 MiB
            'backupCount': 3,
            'formatter': 'default'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
    },
}


# File upload

CORE_FILE_MAX_SIZE = 31457280  # 30 MiB
CORE_ALLOWED_MIME_TYPES = ('text/plain', 'application/pdf')
CORE_ALLOWED_EXTENSIONS = ('txt', 'pdf')

# NLP

CORE_NUM_KEYWORDS = 30
CORE_MIN_SENTENCE_LENGTH = 15

CORE_YAKE_CANDIDATE_NGRAM = 4
CORE_YAKE_CANDIDATE_WINDOW_SIZE = 18
CORE_YAKE_THRESHOLD = 0.95

CORE_CRP_ROW_MODEL = BASE_DIR / 'ml_models' / 'rf_row.pickle'
CORE_CRP_COLUMN_MODEL = BASE_DIR / 'ml_models' / 'rf_column.pickle'
CORE_CRP_TFIDF_VECTORIZER = BASE_DIR / 'ml_models' / 'tfidf_vectorizer.pickle'

CORE_CRP_COLUMN_THRESHOLD = 0.1
CORE_CRP_ROW_THRESHOLD = 0.1

# Repository settings

CORE_CELL_SIMILARITY_THRESHOLD = 0.3
CORE_IMPACT_SIMILARITY_THRESHOLD = 0.005

CORE_NUM_SIMILAR_DOCUMENTS = 10

CORE_REPOSITORY_PREVIEW_URL = 'http://mesoc-doc.uniri.hr'

# Google Cloud

CORE_GOOGLE_CLOUD_CREDENTIALS = {
    "type": "service_account",
    "project_id": "mesoc-machine-translation",
    "private_key_id": "a5f4968af05903b090d2aac8033da8b7e7cddcf6",
    "private_key": (
        "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC36m/1vLhUMgUD\nBX1"
        "3vUkJAxUvXG2+znEKpYl6KKChrrool1i9ryWjEmnYL03S55XQeJ+aAtaGQnex\nRRy6M39tT6aDwfNUCD4vaxk1Z/3Y1ch+VFk"
        "UUl+x4s20ubgYngWAtaAJxNMKYhrh\nofjZyy3hbHZiQ4HNp9aoMlAoKwuMP993NRJ+KKOxrg5q4VR3B7lqGIXgCbhAnSbI\ni"
        "qfKfm/9S0motYB+GXAxFBXvzzia6BM4E+VvyF8AKAB8cI/y6QnQwyEBJg9l1B9K\nOkLZZpuEXezRm9h5GAx46+5yCKT7NbL4z"
        "FhVoJHDvXPX5ONJtKCHfbUPGq5QoifG\n5MFa67m9AgMBAAECggEALI9GAhVv2aJm2XUOkaDQXbkb/GYaBuVQuSIjXXATfyjs"
        "\n3KHSs96IMWroLyNC6UsH3sMi9Dckz9Gx20bh73FDufHW58xpjp4Spv19VZW1CMC/\nO3BnRsewfNJ1QYjPxFMhBS68MDG6ai"
        "Ub2zgZqXcTTi8vvZ4aiH/WP9k0146aVSfJ\nYPCsoYm+7AI5MONE88s/huOpfJCEDnMNaIA3fNvhyvBrrt9bdkqC1bZAFtLdbc"
        "kq\nG+FLCp+DgD5LpjHYefey3KbO8cZn2x+rFYYBVbRkuaMq9CDnhseZQyrlFBr8a8cC\nQnb2Y75DbKHZUCg/43HpA+bXbkTX"
        "18CSmtbnAHRMcQKBgQDgo3QepfiibdsZNEC8\nhuyy+zXPu1kpIuNvOtn5PutB+ECxMyeaj34u+jkoUgQiDhsvorMofXWUT451"
        "LqH8\n16TQp0qvry+I4p5buYxQCgvGBRA/YtCS2u7q4nptLNYFFhX6gKP2s+vECSyhApLx\nVnyVK5eWw6A/rIyiZkn2wRtMmQ"
        "KBgQDRl49NZrIW45phi9fSztVtb+gEjRUWqG7a\n1BhEw8WRZrc3Z88sKLItxmyOp3F93j/V5yT1FhLx50xkWjBlDDiwwKXTZD"
        "18d8Ev\n9hJvDdmIgQ3vnE9YKehqQ2b7KfdHCkFHYQbK6nbd2lav3RcQtWJ0fxKBjxEu5C4e\nOjuwEM0IxQKBgFQKEnkc0oXB"
        "34PwXn+pYogbHyiWCGcxXDDSrZVnio/llh406w4R\nvL1Kc3O4Kz+qU1Vg4vG07fYMRVlllsiGzGwbCf/r5DarwV7DbdDL0VfF"
        "sSxlhW5L\nZbKOBAswCOliN9q9oZm7+eofHIkn811CY91Sr6WBjkQEA6EF74nW+KWRAoGBANEd\nkpD7YbyMoj+pM1DVpQRnnu"
        "rLiLrumowjCYOygLCt9yeEn6PDhuM9EprSXd3jnXVi\nBfGycHyC9ik6AwcOxpEz5T+gx+gj49Bih8nd26jienETV+bzCTzcuy"
        "blnB55EOCS\n4iAbBzYa3lrhEF5PW0g4cNJrWA2dBJaMK3ljie6xAoGBAJWwKWDKWFMo84RRz7cr\n93+K8lffux++8MkTa+tr"
        "vowtByOmVgXL8bedbEny/Aj7pbWIBQRaOx+NDpuBhOZQ\nqb8Mf9L0hb7sg3ZOK3Yfvmriz4Gqx9v1gtmixArtIOoWFobpnOKf"
        "xP34fvBgMJLF\n9tyE2cJMOKUq3tg8aPaTG1G8\n-----END PRIVATE KEY-----\n"
    ),
    "client_email": "machine-translation-service@mesoc-machine-translation.iam.gserviceaccount.com",
    "client_id": "100302473730419688563",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": (
        "https://www.googleapis.com/robot/v1/metadata/x509/machine-translation-service%40mesoc-machine-translation.iam."
        "gserviceaccount.com"
    )
}

CORE_GOOGLE_GEO_API_KEY = 'AIzaSyBNXScHQ992NTJVSw35bnQSVstElcDamXA'
