"""
Django settings for mesoc_api project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1(9g@&*=vk@bapc77qy1e*28zhj%j*p-90ud*m6elj%g(w1nl-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['api.mesoc.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core.apps.CoreConfig',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mesoc_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mesoc_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/etc/mysql/my.cnf'
        },
        'USER': 'mesoc-api',
        'PASSWORD': 'WB(4)NDz',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'NAME': 'mesoc_api'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.User'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email

EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@mail.mesoc.dev'

CORE_FEEDBACK_EMAIL = 'info@mesoc-project.eu'

ANYMAIL = {
    'IGNORE_RECIPIENT_STATUS': True,

    'MAILGUN_API_KEY': '8e50c6c42b5d016116b4d2ae6eae0138-4de08e90-5e28567d',
    'MAILGUN_API_URL': 'https://api.eu.mailgun.net/v3',
}

# Verification and password reset
CORE_API_BASE_URL = 'http://localhost:8000'
CORE_VERIFICATION_BASE_URL = 'https://app.mesoc.dev/verification'
CORE_PASSWORD_RESET_BASE_URL = 'https://app.mesoc.dev/password_reset'
CORE_PROCESSING_SUCCESS_URL = 'https://app.mesoc.dev/my-documents'
CORE_PROCESSING_FAIL_URL = 'https://app.mesoc.dev/upload-document'

CORE_VERIFICATION_MAX_AGE = 14
CORE_PASSWORD_RESET_MAX_AGE = 14

# Celery

CELERY_BROKER_URL = 'redis://localhost:6379'

# Rest framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.BearerTokenAuthentication'
    ],

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ],

    'DEFAULT_METADATA_CLASS': None
}

# CORS

CORS_ALLOWED_ORIGINS = [
    'https://app.mesoc.dev'
]

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{levelname}] {asctime} {module}: {message}',
            'style': '{'
        }
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/mesoc/mesoc_api.log',
            'maxBytes': 10485760,  # 10 MiB
            'backupCount': 3,
            'formatter': 'default'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
    },
}


# File upload

CORE_FILE_MAX_SIZE = 31457280  # 30 MiB
CORE_ALLOWED_MIME_TYPES = ('text/plain', 'application/pdf')
CORE_ALLOWED_EXTENSIONS = ('txt', 'pdf')

# NLP

CORE_NUM_KEYWORDS = 30
CORE_MIN_SENTENCE_LENGTH = 15

CORE_YAKE_CANDIDATE_NGRAM = 4
CORE_YAKE_CANDIDATE_WINDOW_SIZE = 18
CORE_YAKE_THRESHOLD = 0.95

CORE_CRP_ROW_MODEL = BASE_DIR / 'ml_models' / 'rf_row.pickle'
CORE_CRP_COLUMN_MODEL = BASE_DIR / 'ml_models' / 'rf_column.pickle'
CORE_CRP_TFIDF_VECTORIZER = BASE_DIR / 'ml_models' / 'tfidf_vectorizer.pickle'

CORE_CRP_COLUMN_THRESHOLD = 0.1
CORE_CRP_ROW_THRESHOLD = 0.1

# Repository settings

CORE_CELL_SIMILARITY_THRESHOLD = 0.3
CORE_IMPACT_SIMILARITY_THRESHOLD = 0.005

CORE_NUM_SIMILAR_DOCUMENTS = 10

CORE_REPOSITORY_PREVIEW_URL = 'http://mesoc-doc.uniri.hr'
